### PR TITLE
index db

### PR DESCRIPTION
**Pull request by druiz0992**
## What does this implement/fix? Explain your changes.
Index mongodb with frequent queries

## Does this close any currently open issues?
No

### CODE REVIEW

**Comment by pawelgrzybek** [comment]
This is something that I have been looking at. In my opinion it is going to be much easier to do it in Node.js layer. By doing that we can remove it from bash files on this repo, and deployment repo, and just have a consistent functionality independently of the env.

https://www.mongodb.com/docs/drivers/node/current/fundamentals/indexes/#single-field-indexes

**Comment by druiz0992** [comment]
> This is something that I have been looking at. In my opinion it is going to be much easier to do it in Node.js layer. By doing that we can remove it from bash files on this repo, and deployment repo, and just have a consistent functionality independently of the env.
> 
> https://www.mongodb.com/docs/drivers/node/current/fundamentals/indexes/#single-field-indexes

In my opinion, if your method is quick to develop, go for it. Else, let’s use this simple script. As for consistency,  I use this same script for deployment.

**Comment by pawelgrzybek** [comment]
I wanted to move this one to node.js, but i couldnt make my mind where should i place it, because a few sercives depend on it. So probably it is better to do it outside of Node.js. But…

Does it actually work? This one runs in your local context, but you ideally want to execute this in mongodb container? I think we can do it using some `entrypoint` in a docker-compose.

**Comment by druiz0992** [comment]
> I wanted to move this one to node.js, but i couldnt make my mind where should i place it, because a few sercives depend on it. So probably it is better to do it outside of Node.js. But…
> 
> Does it actually work? This one runs in your local context, but you ideally want to execute this in mongodb container? I think we can do it using some `entrypoint` in a docker-compose.

Yes. It connects with the mongoDb container and executes the commands there

**Comment by pawelgrzybek** [comment]
How does it know to which container should it connect to? Also, it requires a user to have `mongosh` installed.

**Comment by druiz0992** [comment]
> How does it know to which container should it connect to? Also, it requires a user to have `mongosh` installed.

You are right on both accounts!!!

**Pull request closed without merging**
